{
    "Target": {
        "EntitySet": "Capex",
        "Service": "/CapexRequests/Services/service1.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/CapexRequests/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/CapexRequests/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}